version: "2"
linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocyclo
    - godoclint
    - godot
    - gosec
    - govet
    - inamedparam
    - ineffassign
    - iotamixing
    - makezero
    - mirror
    - misspell
    - modernize
    - nilnesserr
    - noctx
    - nosprintfhostport
    - predeclared
    - reassign
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    misspell:
      locale: US
    usestdlibvars:
      http-method: false
      time-layout: true
      crypto-hash: true
      sql-isolation-level: true
      tls-signature-scheme: true
    usetesting:
      os-setenv: true
      os-temp-dir: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
