// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewSourceChangeCreatedV4 creates a new struct pointer that represents
// major version 4 of EiffelSourceChangeCreatedEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 4.x.x
// currently known by this SDK.
func NewSourceChangeCreatedV4() (*SourceChangeCreatedV4, error) {
	var event SourceChangeCreatedV4
	event.Meta.Type = "EiffelSourceChangeCreatedEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][4].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *SourceChangeCreatedV4) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]SCCV4Link, 0)
	}
	s := struct {
		Data  *SCCV4Data  `json:"data"`
		Links []SCCV4Link `json:"links"`
		Meta  *SCCV4Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

// String returns the JSON encoding of the event.
func (e *SourceChangeCreatedV4) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

type SourceChangeCreatedV4 struct {
	// Mandatory fields
	Data  SCCV4Data   `json:"data"`
	Links []SCCV4Link `json:"links"`
	Meta  SCCV4Meta   `json:"meta"`

	// Optional fields

}

type SCCV4Data struct {
	// Mandatory fields

	// Optional fields
	Author                SCCV4DataAuthor                `json:"author,omitempty"`
	CcCompositeIdentifier SCCV4DataCcCompositeIdentifier `json:"ccCompositeIdentifier,omitempty"`
	Change                SCCV4DataChange                `json:"change,omitempty"`
	CustomData            []SCCV4DataCustomDatum         `json:"customData,omitempty"`
	GitIdentifier         SCCV4DataGitIdentifier         `json:"gitIdentifier,omitempty"`
	HgIdentifier          SCCV4DataHgIdentifier          `json:"hgIdentifier,omitempty"`
	SvnIdentifier         SCCV4DataSvnIdentifier         `json:"svnIdentifier,omitempty"`
}

type SCCV4DataAuthor struct {
	// Mandatory fields

	// Optional fields
	Email string `json:"email,omitempty"`
	Group string `json:"group,omitempty"`
	ID    string `json:"id,omitempty"`
	Name  string `json:"name,omitempty"`
}

type SCCV4DataCcCompositeIdentifier struct {
	// Mandatory fields
	Branch     string   `json:"branch"`
	ConfigSpec string   `json:"configSpec"`
	Vobs       []string `json:"vobs"`

	// Optional fields

}

type SCCV4DataChange struct {
	// Mandatory fields

	// Optional fields
	Deletions  int64  `json:"deletions,omitempty"`
	Details    string `json:"details,omitempty"`
	Files      string `json:"files,omitempty"`
	ID         string `json:"id,omitempty"`
	Insertions int64  `json:"insertions,omitempty"`
	Tracker    string `json:"tracker,omitempty"`
}

type SCCV4DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type SCCV4DataGitIdentifier struct {
	// Mandatory fields
	CommitID string `json:"commitId"`
	RepoURI  string `json:"repoUri"`

	// Optional fields
	Branch   string `json:"branch,omitempty"`
	RepoName string `json:"repoName,omitempty"`
}

type SCCV4DataHgIdentifier struct {
	// Mandatory fields
	CommitID string `json:"commitId"`
	RepoURI  string `json:"repoUri"`

	// Optional fields
	Branch   string `json:"branch,omitempty"`
	RepoName string `json:"repoName,omitempty"`
}

type SCCV4DataSvnIdentifier struct {
	// Mandatory fields
	Directory string `json:"directory"`
	RepoURI   string `json:"repoUri"`
	Revision  int64  `json:"revision"`

	// Optional fields
	RepoName string `json:"repoName,omitempty"`
}

type SCCV4Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields
	DomainID string `json:"domainId,omitempty"`
}

type SCCV4Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security SCCV4MetaSecurity `json:"security,omitempty"`
	Source   SCCV4MetaSource   `json:"source,omitempty"`
	Tags     []string          `json:"tags,omitempty"`
}

type SCCV4MetaSecurity struct {
	// Mandatory fields
	AuthorIdentity string `json:"authorIdentity"`

	// Optional fields
	IntegrityProtection SCCV4MetaSecurityIntegrityProtection  `json:"integrityProtection,omitempty"`
	SequenceProtection  []SCCV4MetaSecuritySequenceProtection `json:"sequenceProtection,omitempty"`
}

type SCCV4MetaSecurityIntegrityProtection struct {
	// Mandatory fields
	Alg       SCCV4MetaSecurityIntegrityProtectionAlg `json:"alg"`
	Signature string                                  `json:"signature"`

	// Optional fields
	PublicKey string `json:"publicKey,omitempty"`
}

type SCCV4MetaSecurityIntegrityProtectionAlg string

const (
	SCCV4MetaSecurityIntegrityProtectionAlg_HS256 SCCV4MetaSecurityIntegrityProtectionAlg = "HS256"
	SCCV4MetaSecurityIntegrityProtectionAlg_HS384 SCCV4MetaSecurityIntegrityProtectionAlg = "HS384"
	SCCV4MetaSecurityIntegrityProtectionAlg_HS512 SCCV4MetaSecurityIntegrityProtectionAlg = "HS512"
	SCCV4MetaSecurityIntegrityProtectionAlg_RS256 SCCV4MetaSecurityIntegrityProtectionAlg = "RS256"
	SCCV4MetaSecurityIntegrityProtectionAlg_RS384 SCCV4MetaSecurityIntegrityProtectionAlg = "RS384"
	SCCV4MetaSecurityIntegrityProtectionAlg_RS512 SCCV4MetaSecurityIntegrityProtectionAlg = "RS512"
	SCCV4MetaSecurityIntegrityProtectionAlg_ES256 SCCV4MetaSecurityIntegrityProtectionAlg = "ES256"
	SCCV4MetaSecurityIntegrityProtectionAlg_ES384 SCCV4MetaSecurityIntegrityProtectionAlg = "ES384"
	SCCV4MetaSecurityIntegrityProtectionAlg_ES512 SCCV4MetaSecurityIntegrityProtectionAlg = "ES512"
	SCCV4MetaSecurityIntegrityProtectionAlg_PS256 SCCV4MetaSecurityIntegrityProtectionAlg = "PS256"
	SCCV4MetaSecurityIntegrityProtectionAlg_PS384 SCCV4MetaSecurityIntegrityProtectionAlg = "PS384"
	SCCV4MetaSecurityIntegrityProtectionAlg_PS512 SCCV4MetaSecurityIntegrityProtectionAlg = "PS512"
)

type SCCV4MetaSecuritySequenceProtection struct {
	// Mandatory fields
	Position     int64  `json:"position"`
	SequenceName string `json:"sequenceName"`

	// Optional fields

}

type SCCV4MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string `json:"domainId,omitempty"`
	Host       string `json:"host,omitempty"`
	Name       string `json:"name,omitempty"`
	Serializer string `json:"serializer,omitempty"`
	URI        string `json:"uri,omitempty"`
}
