// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"github.com/clarketm/json"
)

// MarshalJSON returns the JSON encoding of the event.
func (e *SourceChangeCreatedV2) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]SCCV2Link, 0)
	}
	s := struct {
		Data  *SCCV2Data  `json:"data"`
		Links []SCCV2Link `json:"links"`
		Meta  *SCCV2Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

// String returns the JSON encoding of the event.
func (e *SourceChangeCreatedV2) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

type SourceChangeCreatedV2 struct {
	// Mandatory fields
	Data  SCCV2Data   `json:"data"`
	Links []SCCV2Link `json:"links"`
	Meta  SCCV2Meta   `json:"meta"`

	// Optional fields

}

type SCCV2Data struct {
	// Mandatory fields

	// Optional fields
	Author                SCCV2DataAuthor                `json:"author,omitempty"`
	CcCompositeIdentifier SCCV2DataCcCompositeIdentifier `json:"ccCompositeIdentifier,omitempty"`
	Change                SCCV2DataChange                `json:"change,omitempty"`
	CustomData            []SCCV2DataCustomDatum         `json:"customData,omitempty"`
	GitIdentifier         SCCV2DataGitIdentifier         `json:"gitIdentifier,omitempty"`
	HgIdentifier          SCCV2DataHgIdentifier          `json:"hgIdentifier,omitempty"`
	SvnIdentifier         SCCV2DataSvnIdentifier         `json:"svnIdentifier,omitempty"`
}

type SCCV2DataAuthor struct {
	// Mandatory fields

	// Optional fields
	Email string `json:"email,omitempty"`
	Group string `json:"group,omitempty"`
	ID    string `json:"id,omitempty"`
	Name  string `json:"name,omitempty"`
}

type SCCV2DataCcCompositeIdentifier struct {
	// Mandatory fields
	Branch     string   `json:"branch"`
	ConfigSpec string   `json:"configSpec"`
	Vobs       []string `json:"vobs"`

	// Optional fields

}

type SCCV2DataChange struct {
	// Mandatory fields

	// Optional fields
	Deletions  int64  `json:"deletions,omitempty"`
	Details    string `json:"details,omitempty"`
	Files      string `json:"files,omitempty"`
	ID         string `json:"id,omitempty"`
	Insertions int64  `json:"insertions,omitempty"`
	Tracker    string `json:"tracker,omitempty"`
}

type SCCV2DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type SCCV2DataGitIdentifier struct {
	// Mandatory fields
	CommitID string `json:"commitId"`
	RepoURI  string `json:"repoUri"`

	// Optional fields
	Branch   string `json:"branch,omitempty"`
	RepoName string `json:"repoName,omitempty"`
}

type SCCV2DataHgIdentifier struct {
	// Mandatory fields
	CommitID string `json:"commitId"`
	RepoURI  string `json:"repoUri"`

	// Optional fields
	Branch   string `json:"branch,omitempty"`
	RepoName string `json:"repoName,omitempty"`
}

type SCCV2DataSvnIdentifier struct {
	// Mandatory fields
	Directory string `json:"directory"`
	RepoURI   string `json:"repoUri"`
	Revision  int64  `json:"revision"`

	// Optional fields
	RepoName string `json:"repoName,omitempty"`
}

type SCCV2Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields

}

type SCCV2Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security SCCV2MetaSecurity `json:"security,omitempty"`
	Source   SCCV2MetaSource   `json:"source,omitempty"`
	Tags     []string          `json:"tags,omitempty"`
}

type SCCV2MetaSecurity struct {
	// Mandatory fields

	// Optional fields
	SDM SCCV2MetaSecuritySDM `json:"sdm,omitempty"`
}

type SCCV2MetaSecuritySDM struct {
	// Mandatory fields
	AuthorIdentity  string `json:"authorIdentity"`
	EncryptedDigest string `json:"encryptedDigest"`

	// Optional fields

}

type SCCV2MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string                    `json:"domainId,omitempty"`
	Host       string                    `json:"host,omitempty"`
	Name       string                    `json:"name,omitempty"`
	Serializer SCCV2MetaSourceSerializer `json:"serializer,omitempty"`
	URI        string                    `json:"uri,omitempty"`
}

type SCCV2MetaSourceSerializer struct {
	// Mandatory fields
	ArtifactID string `json:"artifactId"`
	GroupID    string `json:"groupId"`
	Version    string `json:"version"`

	// Optional fields

}
