// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"fmt"
	"reflect"
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewCompositionDefinedV1 creates a new struct pointer that represents
// major version 1 of EiffelCompositionDefinedEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 1.x.x
// currently known by this SDK.
func NewCompositionDefinedV1(modifiers ...Modifier) (*CompositionDefinedV1, error) {
	var event CompositionDefinedV1
	event.Meta.Type = "EiffelCompositionDefinedEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][1].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	for _, modifier := range modifiers {
		if err := modifier(&event); err != nil {
			return nil, fmt.Errorf("error applying modifier to new CompositionDefinedV1: %w", err)
		}
	}
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *CompositionDefinedV1) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]CDV1Link, 0)
	}
	s := struct {
		Data  *CDV1Data  `json:"data"`
		Links []CDV1Link `json:"links"`
		Meta  *CDV1Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

func (e *CompositionDefinedV1) SetField(fieldName string, value interface{}) error {
	return setField(reflect.ValueOf(e), fieldName, value)
}

// String returns the JSON encoding of the event.
func (e *CompositionDefinedV1) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

var _ FieldSetter = &CompositionDefinedV1{}

type CompositionDefinedV1 struct {
	// Mandatory fields
	Data  CDV1Data   `json:"data"`
	Links []CDV1Link `json:"links"`
	Meta  CDV1Meta   `json:"meta"`

	// Optional fields

}

type CDV1Data struct {
	// Mandatory fields
	Name string `json:"name"`

	// Optional fields
	CustomData []CDV1DataCustomDatum `json:"customData,omitempty"`
	Version    string                `json:"version,omitempty"`
}

type CDV1DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type CDV1Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields

}

type CDV1Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security CDV1MetaSecurity `json:"security,omitempty"`
	Source   CDV1MetaSource   `json:"source,omitempty"`
	Tags     []string         `json:"tags,omitempty"`
}

type CDV1MetaSecurity struct {
	// Mandatory fields

	// Optional fields
	SDM CDV1MetaSecuritySDM `json:"sdm,omitempty"`
}

type CDV1MetaSecuritySDM struct {
	// Mandatory fields
	AuthorIdentity  string `json:"authorIdentity"`
	EncryptedDigest string `json:"encryptedDigest"`

	// Optional fields

}

type CDV1MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string                   `json:"domainId,omitempty"`
	Host       string                   `json:"host,omitempty"`
	Name       string                   `json:"name,omitempty"`
	Serializer CDV1MetaSourceSerializer `json:"serializer,omitempty"`
	URI        string                   `json:"uri,omitempty"`
}

type CDV1MetaSourceSerializer struct {
	// Mandatory fields
	ArtifactID string `json:"artifactId"`
	GroupID    string `json:"groupId"`
	Version    string `json:"version"`

	// Optional fields

}
