// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"fmt"
	"reflect"
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewAnnouncementPublishedV3 creates a new struct pointer that represents
// major version 3 of EiffelAnnouncementPublishedEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 3.x.x
// currently known by this SDK.
func NewAnnouncementPublishedV3(modifiers ...Modifier) (*AnnouncementPublishedV3, error) {
	var event AnnouncementPublishedV3
	event.Meta.Type = "EiffelAnnouncementPublishedEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][3].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	for _, modifier := range modifiers {
		if err := modifier(&event); err != nil {
			return nil, fmt.Errorf("error applying modifier to new AnnouncementPublishedV3: %w", err)
		}
	}
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *AnnouncementPublishedV3) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]AnnPV3Link, 0)
	}
	s := struct {
		Data  *AnnPV3Data  `json:"data"`
		Links []AnnPV3Link `json:"links"`
		Meta  *AnnPV3Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

func (e *AnnouncementPublishedV3) SetField(fieldName string, value interface{}) error {
	return setField(reflect.ValueOf(e), fieldName, value)
}

// String returns the JSON encoding of the event.
func (e *AnnouncementPublishedV3) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

var _ FieldSetter = &AnnouncementPublishedV3{}

type AnnouncementPublishedV3 struct {
	// Mandatory fields
	Data  AnnPV3Data   `json:"data"`
	Links []AnnPV3Link `json:"links"`
	Meta  AnnPV3Meta   `json:"meta"`

	// Optional fields

}

type AnnPV3Data struct {
	// Mandatory fields
	Body     string             `json:"body"`
	Heading  string             `json:"heading"`
	Severity AnnPV3DataSeverity `json:"severity"`

	// Optional fields
	CustomData []AnnPV3DataCustomDatum `json:"customData,omitempty"`
	URI        string                  `json:"uri,omitempty"`
}

type AnnPV3DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type AnnPV3DataSeverity string

const (
	AnnPV3DataSeverity_Minor    AnnPV3DataSeverity = "MINOR"
	AnnPV3DataSeverity_Major    AnnPV3DataSeverity = "MAJOR"
	AnnPV3DataSeverity_Critical AnnPV3DataSeverity = "CRITICAL"
	AnnPV3DataSeverity_Blocker  AnnPV3DataSeverity = "BLOCKER"
	AnnPV3DataSeverity_Closed   AnnPV3DataSeverity = "CLOSED"
	AnnPV3DataSeverity_Canceled AnnPV3DataSeverity = "CANCELED"
)

type AnnPV3Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields
	DomainID string `json:"domainId,omitempty"`
}

type AnnPV3Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security AnnPV3MetaSecurity `json:"security,omitempty"`
	Source   AnnPV3MetaSource   `json:"source,omitempty"`
	Tags     []string           `json:"tags,omitempty"`
}

type AnnPV3MetaSecurity struct {
	// Mandatory fields
	AuthorIdentity string `json:"authorIdentity"`

	// Optional fields
	IntegrityProtection AnnPV3MetaSecurityIntegrityProtection  `json:"integrityProtection,omitempty"`
	SequenceProtection  []AnnPV3MetaSecuritySequenceProtection `json:"sequenceProtection,omitempty"`
}

type AnnPV3MetaSecurityIntegrityProtection struct {
	// Mandatory fields
	Alg       AnnPV3MetaSecurityIntegrityProtectionAlg `json:"alg"`
	Signature string                                   `json:"signature"`

	// Optional fields
	PublicKey string `json:"publicKey,omitempty"`
}

type AnnPV3MetaSecurityIntegrityProtectionAlg string

const (
	AnnPV3MetaSecurityIntegrityProtectionAlg_HS256 AnnPV3MetaSecurityIntegrityProtectionAlg = "HS256"
	AnnPV3MetaSecurityIntegrityProtectionAlg_HS384 AnnPV3MetaSecurityIntegrityProtectionAlg = "HS384"
	AnnPV3MetaSecurityIntegrityProtectionAlg_HS512 AnnPV3MetaSecurityIntegrityProtectionAlg = "HS512"
	AnnPV3MetaSecurityIntegrityProtectionAlg_RS256 AnnPV3MetaSecurityIntegrityProtectionAlg = "RS256"
	AnnPV3MetaSecurityIntegrityProtectionAlg_RS384 AnnPV3MetaSecurityIntegrityProtectionAlg = "RS384"
	AnnPV3MetaSecurityIntegrityProtectionAlg_RS512 AnnPV3MetaSecurityIntegrityProtectionAlg = "RS512"
	AnnPV3MetaSecurityIntegrityProtectionAlg_ES256 AnnPV3MetaSecurityIntegrityProtectionAlg = "ES256"
	AnnPV3MetaSecurityIntegrityProtectionAlg_ES384 AnnPV3MetaSecurityIntegrityProtectionAlg = "ES384"
	AnnPV3MetaSecurityIntegrityProtectionAlg_ES512 AnnPV3MetaSecurityIntegrityProtectionAlg = "ES512"
	AnnPV3MetaSecurityIntegrityProtectionAlg_PS256 AnnPV3MetaSecurityIntegrityProtectionAlg = "PS256"
	AnnPV3MetaSecurityIntegrityProtectionAlg_PS384 AnnPV3MetaSecurityIntegrityProtectionAlg = "PS384"
	AnnPV3MetaSecurityIntegrityProtectionAlg_PS512 AnnPV3MetaSecurityIntegrityProtectionAlg = "PS512"
)

type AnnPV3MetaSecuritySequenceProtection struct {
	// Mandatory fields
	Position     int64  `json:"position"`
	SequenceName string `json:"sequenceName"`

	// Optional fields

}

type AnnPV3MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string `json:"domainId,omitempty"`
	Host       string `json:"host,omitempty"`
	Name       string `json:"name,omitempty"`
	Serializer string `json:"serializer,omitempty"`
	URI        string `json:"uri,omitempty"`
}
