// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"github.com/clarketm/json"
)

// MarshalJSON returns the JSON encoding of the event.
func (e *TestExecutionRecipeCollectionCreatedV1) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]TERCCV1Link, 0)
	}
	s := struct {
		Data  *TERCCV1Data  `json:"data"`
		Links []TERCCV1Link `json:"links"`
		Meta  *TERCCV1Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

// String returns the JSON encoding of the event.
func (e *TestExecutionRecipeCollectionCreatedV1) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

type TestExecutionRecipeCollectionCreatedV1 struct {
	// Mandatory fields
	Data  TERCCV1Data   `json:"data"`
	Links []TERCCV1Link `json:"links"`
	Meta  TERCCV1Meta   `json:"meta"`

	// Optional fields

}

type TERCCV1Data struct {
	// Mandatory fields
	SelectionStrategy TERCCV1DataSelectionStrategy `json:"selectionStrategy"`

	// Optional fields
	Batches    []TERCCV1DataBatch       `json:"batches,omitempty"`
	BatchesURI string                   `json:"batchesUri,omitempty"`
	CustomData []TERCCV1DataCustomDatum `json:"customData,omitempty"`
}

type TERCCV1DataBatch struct {
	// Mandatory fields
	Priority int64                    `json:"priority"`
	Recipes  []TERCCV1DataBatchRecipe `json:"recipes"`

	// Optional fields
	Dependencies []TERCCV1DataBatchDependency `json:"dependencies,omitempty"`
	Name         string                       `json:"name,omitempty"`
}

type TERCCV1DataBatchDependency struct {
	// Mandatory fields
	Dependency string `json:"dependency"`
	Dependent  string `json:"dependent"`

	// Optional fields

}

type TERCCV1DataBatchRecipe struct {
	// Mandatory fields
	ID       string                         `json:"id"`
	TestCase TERCCV1DataBatchRecipeTestCase `json:"testCase"`

	// Optional fields
	Constraints interface{} `json:"constraints,omitempty"`
}

type TERCCV1DataBatchRecipeTestCase struct {
	// Mandatory fields
	ID string `json:"id"`

	// Optional fields
	Tracker string `json:"tracker,omitempty"`
	URI     string `json:"uri,omitempty"`
}

type TERCCV1DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type TERCCV1DataSelectionStrategy struct {
	// Mandatory fields
	ID string `json:"id"`

	// Optional fields
	Tracker string `json:"tracker,omitempty"`
	URI     string `json:"uri,omitempty"`
}

type TERCCV1Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields

}

type TERCCV1Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security TERCCV1MetaSecurity `json:"security,omitempty"`
	Source   TERCCV1MetaSource   `json:"source,omitempty"`
	Tags     []string            `json:"tags,omitempty"`
}

type TERCCV1MetaSecurity struct {
	// Mandatory fields

	// Optional fields
	SDM TERCCV1MetaSecuritySDM `json:"sdm,omitempty"`
}

type TERCCV1MetaSecuritySDM struct {
	// Mandatory fields
	AuthorIdentity  string `json:"authorIdentity"`
	EncryptedDigest string `json:"encryptedDigest"`

	// Optional fields

}

type TERCCV1MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string                      `json:"domainId,omitempty"`
	Host       string                      `json:"host,omitempty"`
	Name       string                      `json:"name,omitempty"`
	Serializer TERCCV1MetaSourceSerializer `json:"serializer,omitempty"`
	URI        string                      `json:"uri,omitempty"`
}

type TERCCV1MetaSourceSerializer struct {
	// Mandatory fields
	ArtifactID string `json:"artifactId"`
	GroupID    string `json:"groupId"`
	Version    string `json:"version"`

	// Optional fields

}
