// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"fmt"
	"reflect"
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewTestCaseTriggeredV1 creates a new struct pointer that represents
// major version 1 of EiffelTestCaseTriggeredEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 1.x.x
// currently known by this SDK.
func NewTestCaseTriggeredV1(modifiers ...Modifier) (*TestCaseTriggeredV1, error) {
	var event TestCaseTriggeredV1
	event.Meta.Type = "EiffelTestCaseTriggeredEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][1].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	for _, modifier := range modifiers {
		if err := modifier(&event); err != nil {
			return nil, fmt.Errorf("error applying modifier to new TestCaseTriggeredV1: %w", err)
		}
	}
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *TestCaseTriggeredV1) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]TCTV1Link, 0)
	}
	s := struct {
		Data  *TCTV1Data  `json:"data"`
		Links []TCTV1Link `json:"links"`
		Meta  *TCTV1Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

func (e *TestCaseTriggeredV1) SetField(fieldName string, value interface{}) error {
	return setField(reflect.ValueOf(e), fieldName, value)
}

// String returns the JSON encoding of the event.
func (e *TestCaseTriggeredV1) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

var _ FieldSetter = &TestCaseTriggeredV1{}

type TestCaseTriggeredV1 struct {
	// Mandatory fields
	Data  TCTV1Data   `json:"data"`
	Links []TCTV1Link `json:"links"`
	Meta  TCTV1Meta   `json:"meta"`

	// Optional fields

}

type TCTV1Data struct {
	// Mandatory fields
	TestCase TCTV1DataTestCase `json:"testCase"`

	// Optional fields
	CustomData    []TCTV1DataCustomDatum `json:"customData,omitempty"`
	ExecutionType TCTV1DataExecutionType `json:"executionType,omitempty"`
	Parameters    []TCTV1DataParameter   `json:"parameters,omitempty"`
	RecipeID      string                 `json:"recipeId,omitempty"`
	Triggers      []TCTV1DataTrigger     `json:"triggers,omitempty"`
}

type TCTV1DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type TCTV1DataExecutionType string

const (
	TCTV1DataExecutionType_Manual        TCTV1DataExecutionType = "MANUAL"
	TCTV1DataExecutionType_SemiAutomated TCTV1DataExecutionType = "SEMI_AUTOMATED"
	TCTV1DataExecutionType_Automated     TCTV1DataExecutionType = "AUTOMATED"
	TCTV1DataExecutionType_Other         TCTV1DataExecutionType = "OTHER"
)

type TCTV1DataParameter struct {
	// Mandatory fields
	Name  string `json:"name"`
	Value string `json:"value"`

	// Optional fields

}

type TCTV1DataTestCase struct {
	// Mandatory fields
	ID string `json:"id"`

	// Optional fields
	Tracker string `json:"tracker,omitempty"`
	URI     string `json:"uri,omitempty"`
	Version string `json:"version,omitempty"`
}

type TCTV1DataTrigger struct {
	// Mandatory fields
	Type TCTV1DataTriggerType `json:"type"`

	// Optional fields
	Description string `json:"description,omitempty"`
}

type TCTV1DataTriggerType string

const (
	TCTV1DataTriggerType_Manual       TCTV1DataTriggerType = "MANUAL"
	TCTV1DataTriggerType_EiffelEvent  TCTV1DataTriggerType = "EIFFEL_EVENT"
	TCTV1DataTriggerType_SourceChange TCTV1DataTriggerType = "SOURCE_CHANGE"
	TCTV1DataTriggerType_Timer        TCTV1DataTriggerType = "TIMER"
	TCTV1DataTriggerType_Other        TCTV1DataTriggerType = "OTHER"
)

type TCTV1Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields

}

type TCTV1Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security TCTV1MetaSecurity `json:"security,omitempty"`
	Source   TCTV1MetaSource   `json:"source,omitempty"`
	Tags     []string          `json:"tags,omitempty"`
}

type TCTV1MetaSecurity struct {
	// Mandatory fields

	// Optional fields
	SDM TCTV1MetaSecuritySDM `json:"sdm,omitempty"`
}

type TCTV1MetaSecuritySDM struct {
	// Mandatory fields
	AuthorIdentity  string `json:"authorIdentity"`
	EncryptedDigest string `json:"encryptedDigest"`

	// Optional fields

}

type TCTV1MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string                    `json:"domainId,omitempty"`
	Host       string                    `json:"host,omitempty"`
	Name       string                    `json:"name,omitempty"`
	Serializer TCTV1MetaSourceSerializer `json:"serializer,omitempty"`
	URI        string                    `json:"uri,omitempty"`
}

type TCTV1MetaSourceSerializer struct {
	// Mandatory fields
	ArtifactID string `json:"artifactId"`
	GroupID    string `json:"groupId"`
	Version    string `json:"version"`

	// Optional fields

}
