// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewTestCaseTriggeredV3 creates a new struct pointer that represents
// major version 3 of EiffelTestCaseTriggeredEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 3.x.x
// currently known by this SDK.
func NewTestCaseTriggeredV3() (*TestCaseTriggeredV3, error) {
	var event TestCaseTriggeredV3
	event.Meta.Type = "EiffelTestCaseTriggeredEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][3].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *TestCaseTriggeredV3) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]TCTV3Link, 0)
	}
	s := struct {
		Data  *TCTV3Data  `json:"data"`
		Links []TCTV3Link `json:"links"`
		Meta  *TCTV3Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

// String returns the JSON encoding of the event.
func (e *TestCaseTriggeredV3) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

type TestCaseTriggeredV3 struct {
	// Mandatory fields
	Data  TCTV3Data   `json:"data"`
	Links []TCTV3Link `json:"links"`
	Meta  TCTV3Meta   `json:"meta"`

	// Optional fields

}

type TCTV3Data struct {
	// Mandatory fields
	TestCase TCTV3DataTestCase `json:"testCase"`

	// Optional fields
	CustomData    []TCTV3DataCustomDatum `json:"customData,omitempty"`
	ExecutionType TCTV3DataExecutionType `json:"executionType,omitempty"`
	Parameters    []TCTV3DataParameter   `json:"parameters,omitempty"`
	RecipeID      string                 `json:"recipeId,omitempty"`
	Triggers      []TCTV3DataTrigger     `json:"triggers,omitempty"`
}

type TCTV3DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type TCTV3DataExecutionType string

const (
	TCTV3DataExecutionType_Manual        TCTV3DataExecutionType = "MANUAL"
	TCTV3DataExecutionType_SemiAutomated TCTV3DataExecutionType = "SEMI_AUTOMATED"
	TCTV3DataExecutionType_Automated     TCTV3DataExecutionType = "AUTOMATED"
	TCTV3DataExecutionType_Other         TCTV3DataExecutionType = "OTHER"
)

type TCTV3DataParameter struct {
	// Mandatory fields
	Name  string `json:"name"`
	Value string `json:"value"`

	// Optional fields

}

type TCTV3DataTestCase struct {
	// Mandatory fields
	ID string `json:"id"`

	// Optional fields
	Tracker string `json:"tracker,omitempty"`
	URI     string `json:"uri,omitempty"`
	Version string `json:"version,omitempty"`
}

type TCTV3DataTrigger struct {
	// Mandatory fields
	Type TCTV3DataTriggerType `json:"type"`

	// Optional fields
	Description string `json:"description,omitempty"`
}

type TCTV3DataTriggerType string

const (
	TCTV3DataTriggerType_Manual       TCTV3DataTriggerType = "MANUAL"
	TCTV3DataTriggerType_EiffelEvent  TCTV3DataTriggerType = "EIFFEL_EVENT"
	TCTV3DataTriggerType_SourceChange TCTV3DataTriggerType = "SOURCE_CHANGE"
	TCTV3DataTriggerType_Timer        TCTV3DataTriggerType = "TIMER"
	TCTV3DataTriggerType_Other        TCTV3DataTriggerType = "OTHER"
)

type TCTV3Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields
	DomainID string `json:"domainId,omitempty"`
}

type TCTV3Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security TCTV3MetaSecurity `json:"security,omitempty"`
	Source   TCTV3MetaSource   `json:"source,omitempty"`
	Tags     []string          `json:"tags,omitempty"`
}

type TCTV3MetaSecurity struct {
	// Mandatory fields
	AuthorIdentity string `json:"authorIdentity"`

	// Optional fields
	IntegrityProtection TCTV3MetaSecurityIntegrityProtection  `json:"integrityProtection,omitempty"`
	SequenceProtection  []TCTV3MetaSecuritySequenceProtection `json:"sequenceProtection,omitempty"`
}

type TCTV3MetaSecurityIntegrityProtection struct {
	// Mandatory fields
	Alg       TCTV3MetaSecurityIntegrityProtectionAlg `json:"alg"`
	Signature string                                  `json:"signature"`

	// Optional fields
	PublicKey string `json:"publicKey,omitempty"`
}

type TCTV3MetaSecurityIntegrityProtectionAlg string

const (
	TCTV3MetaSecurityIntegrityProtectionAlg_HS256 TCTV3MetaSecurityIntegrityProtectionAlg = "HS256"
	TCTV3MetaSecurityIntegrityProtectionAlg_HS384 TCTV3MetaSecurityIntegrityProtectionAlg = "HS384"
	TCTV3MetaSecurityIntegrityProtectionAlg_HS512 TCTV3MetaSecurityIntegrityProtectionAlg = "HS512"
	TCTV3MetaSecurityIntegrityProtectionAlg_RS256 TCTV3MetaSecurityIntegrityProtectionAlg = "RS256"
	TCTV3MetaSecurityIntegrityProtectionAlg_RS384 TCTV3MetaSecurityIntegrityProtectionAlg = "RS384"
	TCTV3MetaSecurityIntegrityProtectionAlg_RS512 TCTV3MetaSecurityIntegrityProtectionAlg = "RS512"
	TCTV3MetaSecurityIntegrityProtectionAlg_ES256 TCTV3MetaSecurityIntegrityProtectionAlg = "ES256"
	TCTV3MetaSecurityIntegrityProtectionAlg_ES384 TCTV3MetaSecurityIntegrityProtectionAlg = "ES384"
	TCTV3MetaSecurityIntegrityProtectionAlg_ES512 TCTV3MetaSecurityIntegrityProtectionAlg = "ES512"
	TCTV3MetaSecurityIntegrityProtectionAlg_PS256 TCTV3MetaSecurityIntegrityProtectionAlg = "PS256"
	TCTV3MetaSecurityIntegrityProtectionAlg_PS384 TCTV3MetaSecurityIntegrityProtectionAlg = "PS384"
	TCTV3MetaSecurityIntegrityProtectionAlg_PS512 TCTV3MetaSecurityIntegrityProtectionAlg = "PS512"
)

type TCTV3MetaSecuritySequenceProtection struct {
	// Mandatory fields
	Position     int64  `json:"position"`
	SequenceName string `json:"sequenceName"`

	// Optional fields

}

type TCTV3MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string `json:"domainId,omitempty"`
	Host       string `json:"host,omitempty"`
	Name       string `json:"name,omitempty"`
	Serializer string `json:"serializer,omitempty"`
	URI        string `json:"uri,omitempty"`
}
