// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"fmt"
	"reflect"
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewTestSuiteFinishedV2 creates a new struct pointer that represents
// major version 2 of EiffelTestSuiteFinishedEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 2.x.x
// currently known by this SDK.
func NewTestSuiteFinishedV2(modifiers ...Modifier) (*TestSuiteFinishedV2, error) {
	var event TestSuiteFinishedV2
	event.Meta.Type = "EiffelTestSuiteFinishedEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][2].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	for _, modifier := range modifiers {
		if err := modifier(&event); err != nil {
			return nil, fmt.Errorf("error applying modifier to new TestSuiteFinishedV2: %w", err)
		}
	}
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *TestSuiteFinishedV2) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]TSFV2Link, 0)
	}
	s := struct {
		Data  *TSFV2Data  `json:"data"`
		Links []TSFV2Link `json:"links"`
		Meta  *TSFV2Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

func (e *TestSuiteFinishedV2) SetField(fieldName string, value interface{}) error {
	return setField(reflect.ValueOf(e), fieldName, value)
}

// String returns the JSON encoding of the event.
func (e *TestSuiteFinishedV2) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

var _ FieldSetter = &TestSuiteFinishedV2{}
var _ MetaTeller = &TestSuiteFinishedV2{}

// ID returns the value of the meta.id field.
func (e TestSuiteFinishedV2) ID() string {
	return e.Meta.ID
}

// Type returns the value of the meta.type field.
func (e TestSuiteFinishedV2) Type() string {
	return e.Meta.Type
}

// Version returns the value of the meta.version field.
func (e TestSuiteFinishedV2) Version() string {
	return e.Meta.Version
}

// Time returns the value of the meta.time field.
func (e TestSuiteFinishedV2) Time() int64 {
	return e.Meta.Time
}

// DomainID returns the value of the meta.source.domainId field.
func (e TestSuiteFinishedV2) DomainID() string {
	return e.Meta.Source.DomainID
}

type TestSuiteFinishedV2 struct {
	// Mandatory fields
	Data  TSFV2Data  `json:"data"`
	Links TSFV2Links `json:"links"`
	Meta  TSFV2Meta  `json:"meta"`

	// Optional fields

}

type TSFV2Data struct {
	// Mandatory fields

	// Optional fields
	CustomData     []TSFV2DataCustomDatum   `json:"customData,omitempty"`
	Outcome        TSFV2DataOutcome         `json:"outcome,omitempty"`
	PersistentLogs []TSFV2DataPersistentLog `json:"persistentLogs,omitempty"`
}

type TSFV2DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type TSFV2DataOutcome struct {
	// Mandatory fields

	// Optional fields
	Conclusion  TSFV2DataOutcomeConclusion `json:"conclusion,omitempty"`
	Description string                     `json:"description,omitempty"`
	Verdict     TSFV2DataOutcomeVerdict    `json:"verdict,omitempty"`
}

type TSFV2DataOutcomeConclusion string

const (
	TSFV2DataOutcomeConclusion_Successful   TSFV2DataOutcomeConclusion = "SUCCESSFUL"
	TSFV2DataOutcomeConclusion_Failed       TSFV2DataOutcomeConclusion = "FAILED"
	TSFV2DataOutcomeConclusion_Aborted      TSFV2DataOutcomeConclusion = "ABORTED"
	TSFV2DataOutcomeConclusion_TimedOut     TSFV2DataOutcomeConclusion = "TIMED_OUT"
	TSFV2DataOutcomeConclusion_Inconclusive TSFV2DataOutcomeConclusion = "INCONCLUSIVE"
)

type TSFV2DataOutcomeVerdict string

const (
	TSFV2DataOutcomeVerdict_Passed       TSFV2DataOutcomeVerdict = "PASSED"
	TSFV2DataOutcomeVerdict_Failed       TSFV2DataOutcomeVerdict = "FAILED"
	TSFV2DataOutcomeVerdict_Inconclusive TSFV2DataOutcomeVerdict = "INCONCLUSIVE"
)

type TSFV2DataPersistentLog struct {
	// Mandatory fields
	Name string `json:"name"`
	URI  string `json:"uri"`

	// Optional fields

}

// TSFV2Links represents a slice of TSFV2Link values with helper methods
// for adding new links.
type TSFV2Links []TSFV2Link

// Add adds a new link of the specified type to a target event.
func (links *TSFV2Links) Add(linkType string, target MetaTeller) {
	*links = append(*links, TSFV2Link{Target: target.ID(), Type: linkType})
}

// Add adds a new link of the specified type to a target event identified by an ID.
func (links *TSFV2Links) AddByID(linkType string, target string) {
	*links = append(*links, TSFV2Link{Target: target, Type: linkType})
}

type TSFV2Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields

}

type TSFV2Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security TSFV2MetaSecurity `json:"security,omitempty"`
	Source   TSFV2MetaSource   `json:"source,omitempty"`
	Tags     []string          `json:"tags,omitempty"`
}

type TSFV2MetaSecurity struct {
	// Mandatory fields

	// Optional fields
	SDM TSFV2MetaSecuritySDM `json:"sdm,omitempty"`
}

type TSFV2MetaSecuritySDM struct {
	// Mandatory fields
	AuthorIdentity  string `json:"authorIdentity"`
	EncryptedDigest string `json:"encryptedDigest"`

	// Optional fields

}

type TSFV2MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string `json:"domainId,omitempty"`
	Host       string `json:"host,omitempty"`
	Name       string `json:"name,omitempty"`
	Serializer string `json:"serializer,omitempty"`
	URI        string `json:"uri,omitempty"`
}
