// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewEnvironmentDefinedV3 creates a new struct pointer that represents
// major version 3 of EiffelEnvironmentDefinedEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 3.x.x
// currently known by this SDK.
func NewEnvironmentDefinedV3() (*EnvironmentDefinedV3, error) {
	var event EnvironmentDefinedV3
	event.Meta.Type = "EiffelEnvironmentDefinedEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][3].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *EnvironmentDefinedV3) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]EDV3Link, 0)
	}
	s := struct {
		Data  *EDV3Data  `json:"data"`
		Links []EDV3Link `json:"links"`
		Meta  *EDV3Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

// String returns the JSON encoding of the event.
func (e *EnvironmentDefinedV3) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

type EnvironmentDefinedV3 struct {
	// Mandatory fields
	Data  EDV3Data   `json:"data"`
	Links []EDV3Link `json:"links"`
	Meta  EDV3Meta   `json:"meta"`

	// Optional fields

}

type EDV3Data struct {
	// Mandatory fields
	Name string `json:"name"`

	// Optional fields
	CustomData []EDV3DataCustomDatum `json:"customData,omitempty"`
	Host       EDV3DataHost          `json:"host,omitempty"`
	Image      string                `json:"image,omitempty"`
	URI        string                `json:"uri,omitempty"`
	Version    string                `json:"version,omitempty"`
}

type EDV3DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type EDV3DataHost struct {
	// Mandatory fields
	Name string `json:"name"`
	User string `json:"user"`

	// Optional fields

}

type EDV3Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields
	DomainID string `json:"domainId,omitempty"`
}

type EDV3Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security EDV3MetaSecurity `json:"security,omitempty"`
	Source   EDV3MetaSource   `json:"source,omitempty"`
	Tags     []string         `json:"tags,omitempty"`
}

type EDV3MetaSecurity struct {
	// Mandatory fields
	AuthorIdentity string `json:"authorIdentity"`

	// Optional fields
	IntegrityProtection EDV3MetaSecurityIntegrityProtection  `json:"integrityProtection,omitempty"`
	SequenceProtection  []EDV3MetaSecuritySequenceProtection `json:"sequenceProtection,omitempty"`
}

type EDV3MetaSecurityIntegrityProtection struct {
	// Mandatory fields
	Alg       EDV3MetaSecurityIntegrityProtectionAlg `json:"alg"`
	Signature string                                 `json:"signature"`

	// Optional fields
	PublicKey string `json:"publicKey,omitempty"`
}

type EDV3MetaSecurityIntegrityProtectionAlg string

const (
	EDV3MetaSecurityIntegrityProtectionAlg_HS256 EDV3MetaSecurityIntegrityProtectionAlg = "HS256"
	EDV3MetaSecurityIntegrityProtectionAlg_HS384 EDV3MetaSecurityIntegrityProtectionAlg = "HS384"
	EDV3MetaSecurityIntegrityProtectionAlg_HS512 EDV3MetaSecurityIntegrityProtectionAlg = "HS512"
	EDV3MetaSecurityIntegrityProtectionAlg_RS256 EDV3MetaSecurityIntegrityProtectionAlg = "RS256"
	EDV3MetaSecurityIntegrityProtectionAlg_RS384 EDV3MetaSecurityIntegrityProtectionAlg = "RS384"
	EDV3MetaSecurityIntegrityProtectionAlg_RS512 EDV3MetaSecurityIntegrityProtectionAlg = "RS512"
	EDV3MetaSecurityIntegrityProtectionAlg_ES256 EDV3MetaSecurityIntegrityProtectionAlg = "ES256"
	EDV3MetaSecurityIntegrityProtectionAlg_ES384 EDV3MetaSecurityIntegrityProtectionAlg = "ES384"
	EDV3MetaSecurityIntegrityProtectionAlg_ES512 EDV3MetaSecurityIntegrityProtectionAlg = "ES512"
	EDV3MetaSecurityIntegrityProtectionAlg_PS256 EDV3MetaSecurityIntegrityProtectionAlg = "PS256"
	EDV3MetaSecurityIntegrityProtectionAlg_PS384 EDV3MetaSecurityIntegrityProtectionAlg = "PS384"
	EDV3MetaSecurityIntegrityProtectionAlg_PS512 EDV3MetaSecurityIntegrityProtectionAlg = "PS512"
)

type EDV3MetaSecuritySequenceProtection struct {
	// Mandatory fields
	Position     int64  `json:"position"`
	SequenceName string `json:"sequenceName"`

	// Optional fields

}

type EDV3MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string `json:"domainId,omitempty"`
	Host       string `json:"host,omitempty"`
	Name       string `json:"name,omitempty"`
	Serializer string `json:"serializer,omitempty"`
	URI        string `json:"uri,omitempty"`
}
