// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"fmt"
	"reflect"
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewArtifactCreatedV1 creates a new struct pointer that represents
// major version 1 of EiffelArtifactCreatedEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 1.x.x
// currently known by this SDK.
func NewArtifactCreatedV1(modifiers ...Modifier) (*ArtifactCreatedV1, error) {
	var event ArtifactCreatedV1
	event.Meta.Type = "EiffelArtifactCreatedEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][1].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	for _, modifier := range modifiers {
		if err := modifier(&event); err != nil {
			return nil, fmt.Errorf("error applying modifier to new ArtifactCreatedV1: %w", err)
		}
	}
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *ArtifactCreatedV1) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make(EventLinksV1, 0)
	}
	s := struct {
		Data  *ArtCV1Data  `json:"data"`
		Links EventLinksV1 `json:"links"`
		Meta  *MetaV1      `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

func (e *ArtifactCreatedV1) SetField(fieldName string, value interface{}) error {
	return setField(reflect.ValueOf(e), fieldName, value)
}

// String returns the JSON encoding of the event.
func (e *ArtifactCreatedV1) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

var (
	_ CapabilityTeller = &ArtifactCreatedV1{}
	_ FieldSetter      = &ArtifactCreatedV1{}
	_ MetaTeller       = &ArtifactCreatedV1{}
)

// ID returns the value of the meta.id field.
func (e ArtifactCreatedV1) ID() string {
	return e.Meta.ID
}

// Type returns the value of the meta.type field.
func (e ArtifactCreatedV1) Type() string {
	return e.Meta.Type
}

// Version returns the value of the meta.version field.
func (e ArtifactCreatedV1) Version() string {
	return e.Meta.Version
}

// Time returns the value of the meta.time field.
func (e ArtifactCreatedV1) Time() int64 {
	return e.Meta.Time
}

// DomainID returns the value of the meta.source.domainId field.
func (e ArtifactCreatedV1) DomainID() string {
	return e.Meta.Source.DomainID
}

// SupportsSigning returns true if the event supports signatures according
// to V3 of the meta field, i.e. events where the signature is found under
// meta.security.integrityProtection.
func (e ArtifactCreatedV1) SupportsSigning() bool {
	return false
}

type ArtifactCreatedV1 struct {
	// Mandatory fields
	Data  ArtCV1Data   `json:"data"`
	Links EventLinksV1 `json:"links"`
	Meta  MetaV1       `json:"meta"`

	// Optional fields

}

type ArtCV1Data struct {
	// Mandatory fields
	Gav ArtCV1DataGav `json:"gav"`

	// Optional fields
	BuildCommand           string                           `json:"buildCommand,omitempty"`
	CustomData             []CustomDataV1                   `json:"customData,omitempty"`
	DependsOn              []ArtCV1DataDependsOn            `json:"dependsOn,omitempty"`
	FileInformation        []ArtCV1DataFileInformation      `json:"fileInformation,omitempty"`
	Implements             []ArtCV1DataImplement            `json:"implements,omitempty"`
	Name                   string                           `json:"name,omitempty"`
	RequiresImplementation ArtCV1DataRequiresImplementation `json:"requiresImplementation,omitempty"`
}

type ArtCV1DataDependsOn struct {
	// Mandatory fields
	ArtifactID string `json:"artifactId"`
	GroupID    string `json:"groupId"`
	Version    string `json:"version"`

	// Optional fields

}

type ArtCV1DataFileInformation struct {
	// Mandatory fields
	Classifier string `json:"classifier"`
	Extension  string `json:"extension"`

	// Optional fields

}

type ArtCV1DataGav struct {
	// Mandatory fields
	ArtifactID string `json:"artifactId"`
	GroupID    string `json:"groupId"`
	Version    string `json:"version"`

	// Optional fields

}

type ArtCV1DataImplement struct {
	// Mandatory fields
	ArtifactID string `json:"artifactId"`
	GroupID    string `json:"groupId"`
	Version    string `json:"version"`

	// Optional fields

}

type ArtCV1DataRequiresImplementation string

const (
	ArtCV1DataRequiresImplementation_None       ArtCV1DataRequiresImplementation = "NONE"
	ArtCV1DataRequiresImplementation_Any        ArtCV1DataRequiresImplementation = "ANY"
	ArtCV1DataRequiresImplementation_ExactlyOne ArtCV1DataRequiresImplementation = "EXACTLY_ONE"
	ArtCV1DataRequiresImplementation_AtLeastOne ArtCV1DataRequiresImplementation = "AT_LEAST_ONE"
)
