// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

package eiffelevents

import (
	"fmt"
	"reflect"
	"time"

	"github.com/clarketm/json"
	"github.com/google/uuid"
)

// NewActivityTriggeredV3 creates a new struct pointer that represents
// major version 3 of EiffelActivityTriggeredEvent.
// The returned struct has all required meta members populated.
// The event version is set to the most recent 3.x.x
// currently known by this SDK.
func NewActivityTriggeredV3(modifiers ...Modifier) (*ActivityTriggeredV3, error) {
	var event ActivityTriggeredV3
	event.Meta.Type = "EiffelActivityTriggeredEvent"
	event.Meta.ID = uuid.NewString()
	event.Meta.Version = eventTypeTable[event.Meta.Type][3].latestVersion
	event.Meta.Time = time.Now().UnixMilli()
	for _, modifier := range modifiers {
		if err := modifier(&event); err != nil {
			return nil, fmt.Errorf("error applying modifier to new ActivityTriggeredV3: %w", err)
		}
	}
	return &event, nil
}

// MarshalJSON returns the JSON encoding of the event.
func (e *ActivityTriggeredV3) MarshalJSON() ([]byte, error) {
	// The standard encoding/json package doesn't honor omitempty for
	// non-pointer structs (it doesn't recurse into values, only examines
	// the immediate value). This is a not terribly elegant way of making
	// sure that this struct is marshaled by github.com/clarketm/json
	// without the infinite loop we'd get by just passing the struct to
	// github.com/clarketm/json.Marshal.
	//
	// Make sure the links slice is non-null so that non-initialized slices
	// get serialized as "[]" instead of "null".
	links := e.Links
	if links == nil {
		links = make([]ActTV3Link, 0)
	}
	s := struct {
		Data  *ActTV3Data  `json:"data"`
		Links []ActTV3Link `json:"links"`
		Meta  *ActTV3Meta  `json:"meta"`
	}{
		Data:  &e.Data,
		Links: links,
		Meta:  &e.Meta,
	}
	return json.Marshal(s)
}

func (e *ActivityTriggeredV3) SetField(fieldName string, value interface{}) error {
	return setField(reflect.ValueOf(e), fieldName, value)
}

// String returns the JSON encoding of the event.
func (e *ActivityTriggeredV3) String() string {
	b, err := e.MarshalJSON()
	if err != nil {
		// This should never happen, and if it does happen it's not clear that
		// there's a reasonable way to recover. Returning an error message
		// instead of the JSON string won't end well.
		panic(err)
	}
	return string(b)
}

var _ FieldSetter = &ActivityTriggeredV3{}

type ActivityTriggeredV3 struct {
	// Mandatory fields
	Data  ActTV3Data   `json:"data"`
	Links []ActTV3Link `json:"links"`
	Meta  ActTV3Meta   `json:"meta"`

	// Optional fields

}

type ActTV3Data struct {
	// Mandatory fields
	Name string `json:"name"`

	// Optional fields
	Categories    []string                `json:"categories,omitempty"`
	CustomData    []ActTV3DataCustomDatum `json:"customData,omitempty"`
	ExecutionType ActTV3DataExecutionType `json:"executionType,omitempty"`
	Triggers      []ActTV3DataTrigger     `json:"triggers,omitempty"`
}

type ActTV3DataCustomDatum struct {
	// Mandatory fields
	Key   string      `json:"key"`
	Value interface{} `json:"value"`

	// Optional fields

}

type ActTV3DataExecutionType string

const (
	ActTV3DataExecutionType_Manual        ActTV3DataExecutionType = "MANUAL"
	ActTV3DataExecutionType_SemiAutomated ActTV3DataExecutionType = "SEMI_AUTOMATED"
	ActTV3DataExecutionType_Automated     ActTV3DataExecutionType = "AUTOMATED"
	ActTV3DataExecutionType_Other         ActTV3DataExecutionType = "OTHER"
)

type ActTV3DataTrigger struct {
	// Mandatory fields
	Type ActTV3DataTriggerType `json:"type"`

	// Optional fields
	Description string `json:"description,omitempty"`
}

type ActTV3DataTriggerType string

const (
	ActTV3DataTriggerType_Manual       ActTV3DataTriggerType = "MANUAL"
	ActTV3DataTriggerType_EiffelEvent  ActTV3DataTriggerType = "EIFFEL_EVENT"
	ActTV3DataTriggerType_SourceChange ActTV3DataTriggerType = "SOURCE_CHANGE"
	ActTV3DataTriggerType_Timer        ActTV3DataTriggerType = "TIMER"
	ActTV3DataTriggerType_Other        ActTV3DataTriggerType = "OTHER"
)

type ActTV3Link struct {
	// Mandatory fields
	Target string `json:"target"`
	Type   string `json:"type"`

	// Optional fields

}

type ActTV3Meta struct {
	// Mandatory fields
	ID      string `json:"id"`
	Time    int64  `json:"time"`
	Type    string `json:"type"`
	Version string `json:"version"`

	// Optional fields
	Security ActTV3MetaSecurity `json:"security,omitempty"`
	Source   ActTV3MetaSource   `json:"source,omitempty"`
	Tags     []string           `json:"tags,omitempty"`
}

type ActTV3MetaSecurity struct {
	// Mandatory fields

	// Optional fields
	SDM ActTV3MetaSecuritySDM `json:"sdm,omitempty"`
}

type ActTV3MetaSecuritySDM struct {
	// Mandatory fields
	AuthorIdentity  string `json:"authorIdentity"`
	EncryptedDigest string `json:"encryptedDigest"`

	// Optional fields

}

type ActTV3MetaSource struct {
	// Mandatory fields

	// Optional fields
	DomainID   string `json:"domainId,omitempty"`
	Host       string `json:"host,omitempty"`
	Name       string `json:"name,omitempty"`
	Serializer string `json:"serializer,omitempty"`
	URI        string `json:"uri,omitempty"`
}
