// Copyright Axis Communications AB.
//
// For a full list of individual contributors, please see the commit history.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by editiongen. DO NOT EDIT.

package eiffelevents

import (
	eiffeleventsroot "github.com/eiffel-community/eiffelevents-sdk-go"
)

// ActivityCanceled represents version 3.2.0 of EiffelActivityCanceledEvent.
type ActivityCanceled = eiffeleventsroot.ActivityCanceledV3

// NewActivityCanceled creates a new struct pointer that represents
// version 3.2.0 of EiffelActivityCanceledEvent. The returned struct has
// all required meta members populated.
func NewActivityCanceled(modifiers ...eiffeleventsroot.Modifier) (*ActivityCanceled, error) {
	return eiffeleventsroot.NewActivityCanceledV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// ActivityFinished represents version 3.3.0 of EiffelActivityFinishedEvent.
type ActivityFinished = eiffeleventsroot.ActivityFinishedV3

// NewActivityFinished creates a new struct pointer that represents
// version 3.3.0 of EiffelActivityFinishedEvent. The returned struct has
// all required meta members populated.
func NewActivityFinished(modifiers ...eiffeleventsroot.Modifier) (*ActivityFinished, error) {
	return eiffeleventsroot.NewActivityFinishedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// ActivityStarted represents version 4.3.0 of EiffelActivityStartedEvent.
type ActivityStarted = eiffeleventsroot.ActivityStartedV4

// NewActivityStarted creates a new struct pointer that represents
// version 4.3.0 of EiffelActivityStartedEvent. The returned struct has
// all required meta members populated.
func NewActivityStarted(modifiers ...eiffeleventsroot.Modifier) (*ActivityStarted, error) {
	return eiffeleventsroot.NewActivityStartedV4(append(modifiers, eiffeleventsroot.WithVersion("4.3.0"))...)
}

// ActivityTriggered represents version 4.2.0 of EiffelActivityTriggeredEvent.
type ActivityTriggered = eiffeleventsroot.ActivityTriggeredV4

// NewActivityTriggered creates a new struct pointer that represents
// version 4.2.0 of EiffelActivityTriggeredEvent. The returned struct has
// all required meta members populated.
func NewActivityTriggered(modifiers ...eiffeleventsroot.Modifier) (*ActivityTriggered, error) {
	return eiffeleventsroot.NewActivityTriggeredV4(append(modifiers, eiffeleventsroot.WithVersion("4.2.0"))...)
}

// AnnouncementPublished represents version 3.2.0 of EiffelAnnouncementPublishedEvent.
type AnnouncementPublished = eiffeleventsroot.AnnouncementPublishedV3

// NewAnnouncementPublished creates a new struct pointer that represents
// version 3.2.0 of EiffelAnnouncementPublishedEvent. The returned struct has
// all required meta members populated.
func NewAnnouncementPublished(modifiers ...eiffeleventsroot.Modifier) (*AnnouncementPublished, error) {
	return eiffeleventsroot.NewAnnouncementPublishedV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// ArtifactCreated represents version 3.3.0 of EiffelArtifactCreatedEvent.
type ArtifactCreated = eiffeleventsroot.ArtifactCreatedV3

// NewArtifactCreated creates a new struct pointer that represents
// version 3.3.0 of EiffelArtifactCreatedEvent. The returned struct has
// all required meta members populated.
func NewArtifactCreated(modifiers ...eiffeleventsroot.Modifier) (*ArtifactCreated, error) {
	return eiffeleventsroot.NewArtifactCreatedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// ArtifactPublished represents version 3.3.0 of EiffelArtifactPublishedEvent.
type ArtifactPublished = eiffeleventsroot.ArtifactPublishedV3

// NewArtifactPublished creates a new struct pointer that represents
// version 3.3.0 of EiffelArtifactPublishedEvent. The returned struct has
// all required meta members populated.
func NewArtifactPublished(modifiers ...eiffeleventsroot.Modifier) (*ArtifactPublished, error) {
	return eiffeleventsroot.NewArtifactPublishedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// ArtifactReused represents version 3.2.0 of EiffelArtifactReusedEvent.
type ArtifactReused = eiffeleventsroot.ArtifactReusedV3

// NewArtifactReused creates a new struct pointer that represents
// version 3.2.0 of EiffelArtifactReusedEvent. The returned struct has
// all required meta members populated.
func NewArtifactReused(modifiers ...eiffeleventsroot.Modifier) (*ArtifactReused, error) {
	return eiffeleventsroot.NewArtifactReusedV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// CompositionDefined represents version 3.3.0 of EiffelCompositionDefinedEvent.
type CompositionDefined = eiffeleventsroot.CompositionDefinedV3

// NewCompositionDefined creates a new struct pointer that represents
// version 3.3.0 of EiffelCompositionDefinedEvent. The returned struct has
// all required meta members populated.
func NewCompositionDefined(modifiers ...eiffeleventsroot.Modifier) (*CompositionDefined, error) {
	return eiffeleventsroot.NewCompositionDefinedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// ConfidenceLevelModified represents version 3.2.0 of EiffelConfidenceLevelModifiedEvent.
type ConfidenceLevelModified = eiffeleventsroot.ConfidenceLevelModifiedV3

// NewConfidenceLevelModified creates a new struct pointer that represents
// version 3.2.0 of EiffelConfidenceLevelModifiedEvent. The returned struct has
// all required meta members populated.
func NewConfidenceLevelModified(modifiers ...eiffeleventsroot.Modifier) (*ConfidenceLevelModified, error) {
	return eiffeleventsroot.NewConfidenceLevelModifiedV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// EnvironmentDefined represents version 3.3.0 of EiffelEnvironmentDefinedEvent.
type EnvironmentDefined = eiffeleventsroot.EnvironmentDefinedV3

// NewEnvironmentDefined creates a new struct pointer that represents
// version 3.3.0 of EiffelEnvironmentDefinedEvent. The returned struct has
// all required meta members populated.
func NewEnvironmentDefined(modifiers ...eiffeleventsroot.Modifier) (*EnvironmentDefined, error) {
	return eiffeleventsroot.NewEnvironmentDefinedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// FlowContextDefined represents version 3.2.0 of EiffelFlowContextDefinedEvent.
type FlowContextDefined = eiffeleventsroot.FlowContextDefinedV3

// NewFlowContextDefined creates a new struct pointer that represents
// version 3.2.0 of EiffelFlowContextDefinedEvent. The returned struct has
// all required meta members populated.
func NewFlowContextDefined(modifiers ...eiffeleventsroot.Modifier) (*FlowContextDefined, error) {
	return eiffeleventsroot.NewFlowContextDefinedV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// IssueDefined represents version 3.2.0 of EiffelIssueDefinedEvent.
type IssueDefined = eiffeleventsroot.IssueDefinedV3

// NewIssueDefined creates a new struct pointer that represents
// version 3.2.0 of EiffelIssueDefinedEvent. The returned struct has
// all required meta members populated.
func NewIssueDefined(modifiers ...eiffeleventsroot.Modifier) (*IssueDefined, error) {
	return eiffeleventsroot.NewIssueDefinedV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// IssueVerified represents version 4.2.0 of EiffelIssueVerifiedEvent.
type IssueVerified = eiffeleventsroot.IssueVerifiedV4

// NewIssueVerified creates a new struct pointer that represents
// version 4.2.0 of EiffelIssueVerifiedEvent. The returned struct has
// all required meta members populated.
func NewIssueVerified(modifiers ...eiffeleventsroot.Modifier) (*IssueVerified, error) {
	return eiffeleventsroot.NewIssueVerifiedV4(append(modifiers, eiffeleventsroot.WithVersion("4.2.0"))...)
}

// SourceChangeCreated represents version 4.2.0 of EiffelSourceChangeCreatedEvent.
type SourceChangeCreated = eiffeleventsroot.SourceChangeCreatedV4

// NewSourceChangeCreated creates a new struct pointer that represents
// version 4.2.0 of EiffelSourceChangeCreatedEvent. The returned struct has
// all required meta members populated.
func NewSourceChangeCreated(modifiers ...eiffeleventsroot.Modifier) (*SourceChangeCreated, error) {
	return eiffeleventsroot.NewSourceChangeCreatedV4(append(modifiers, eiffeleventsroot.WithVersion("4.2.0"))...)
}

// SourceChangeSubmitted represents version 3.2.0 of EiffelSourceChangeSubmittedEvent.
type SourceChangeSubmitted = eiffeleventsroot.SourceChangeSubmittedV3

// NewSourceChangeSubmitted creates a new struct pointer that represents
// version 3.2.0 of EiffelSourceChangeSubmittedEvent. The returned struct has
// all required meta members populated.
func NewSourceChangeSubmitted(modifiers ...eiffeleventsroot.Modifier) (*SourceChangeSubmitted, error) {
	return eiffeleventsroot.NewSourceChangeSubmittedV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// TestCaseCanceled represents version 3.2.0 of EiffelTestCaseCanceledEvent.
type TestCaseCanceled = eiffeleventsroot.TestCaseCanceledV3

// NewTestCaseCanceled creates a new struct pointer that represents
// version 3.2.0 of EiffelTestCaseCanceledEvent. The returned struct has
// all required meta members populated.
func NewTestCaseCanceled(modifiers ...eiffeleventsroot.Modifier) (*TestCaseCanceled, error) {
	return eiffeleventsroot.NewTestCaseCanceledV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// TestCaseFinished represents version 3.3.0 of EiffelTestCaseFinishedEvent.
type TestCaseFinished = eiffeleventsroot.TestCaseFinishedV3

// NewTestCaseFinished creates a new struct pointer that represents
// version 3.3.0 of EiffelTestCaseFinishedEvent. The returned struct has
// all required meta members populated.
func NewTestCaseFinished(modifiers ...eiffeleventsroot.Modifier) (*TestCaseFinished, error) {
	return eiffeleventsroot.NewTestCaseFinishedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// TestCaseStarted represents version 3.3.0 of EiffelTestCaseStartedEvent.
type TestCaseStarted = eiffeleventsroot.TestCaseStartedV3

// NewTestCaseStarted creates a new struct pointer that represents
// version 3.3.0 of EiffelTestCaseStartedEvent. The returned struct has
// all required meta members populated.
func NewTestCaseStarted(modifiers ...eiffeleventsroot.Modifier) (*TestCaseStarted, error) {
	return eiffeleventsroot.NewTestCaseStartedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// TestCaseTriggered represents version 3.2.0 of EiffelTestCaseTriggeredEvent.
type TestCaseTriggered = eiffeleventsroot.TestCaseTriggeredV3

// NewTestCaseTriggered creates a new struct pointer that represents
// version 3.2.0 of EiffelTestCaseTriggeredEvent. The returned struct has
// all required meta members populated.
func NewTestCaseTriggered(modifiers ...eiffeleventsroot.Modifier) (*TestCaseTriggered, error) {
	return eiffeleventsroot.NewTestCaseTriggeredV3(append(modifiers, eiffeleventsroot.WithVersion("3.2.0"))...)
}

// TestExecutionRecipeCollectionCreated represents version 4.3.0 of EiffelTestExecutionRecipeCollectionCreatedEvent.
type TestExecutionRecipeCollectionCreated = eiffeleventsroot.TestExecutionRecipeCollectionCreatedV4

// NewTestExecutionRecipeCollectionCreated creates a new struct pointer that represents
// version 4.3.0 of EiffelTestExecutionRecipeCollectionCreatedEvent. The returned struct has
// all required meta members populated.
func NewTestExecutionRecipeCollectionCreated(modifiers ...eiffeleventsroot.Modifier) (*TestExecutionRecipeCollectionCreated, error) {
	return eiffeleventsroot.NewTestExecutionRecipeCollectionCreatedV4(append(modifiers, eiffeleventsroot.WithVersion("4.3.0"))...)
}

// TestSuiteFinished represents version 3.3.0 of EiffelTestSuiteFinishedEvent.
type TestSuiteFinished = eiffeleventsroot.TestSuiteFinishedV3

// NewTestSuiteFinished creates a new struct pointer that represents
// version 3.3.0 of EiffelTestSuiteFinishedEvent. The returned struct has
// all required meta members populated.
func NewTestSuiteFinished(modifiers ...eiffeleventsroot.Modifier) (*TestSuiteFinished, error) {
	return eiffeleventsroot.NewTestSuiteFinishedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}

// TestSuiteStarted represents version 3.3.0 of EiffelTestSuiteStartedEvent.
type TestSuiteStarted = eiffeleventsroot.TestSuiteStartedV3

// NewTestSuiteStarted creates a new struct pointer that represents
// version 3.3.0 of EiffelTestSuiteStartedEvent. The returned struct has
// all required meta members populated.
func NewTestSuiteStarted(modifiers ...eiffeleventsroot.Modifier) (*TestSuiteStarted, error) {
	return eiffeleventsroot.NewTestSuiteStartedV3(append(modifiers, eiffeleventsroot.WithVersion("3.3.0"))...)
}
